const POSTS_ACTION_TYPES = {
    FETCH_POSTS_START:   'posts/FETCH_CATEGORIES_START',
    FETCH_POSTS_SUCCESS: 'posts/FETCH_CATEGORIES_SUCCESS',
    FETCH_POSTS_FAILED:  'posts/FETCH_CATEGORIES_FAILED',
}

export default POSTS_ACTION_TYPES;
