export enum POST_COMMENTS_ACTION_TYPES {
    FETCH_POST_COMMENTS_START   = 'postComments/FETCH_POST_COMMENTS_START',
    FETCH_POST_COMMENTS_SUCCESS = 'postComments/FETCH_POST_COMMENTS_SUCCESS',
    FETCH_POST_COMMENTS_FAILED  = 'postComments/FETCH_POST_COMMENTS_FAILED',
}
